### ISSUE TITLE
On the control plane, Create New RDS instance is disabled

### ISSUE THREAD

**Issue by zzxwill** [upbound/universal-crossplane#107]
### What happened?

On the control plane, `Create New` RDS instance is disabled.

![image](https://user-images.githubusercontent.com/2805315/118769709-0bb4ff00-b8b3-11eb-93b4-65ea57de4a84.png)

### How can we reproduce it?

Follow the steps of https://github.com/upbound/universal-crossplane/blob/main/README.md.

### What environment did it happen in?

Universal Crossplane version: v0.1.0
Kubernetes version (`kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.8-aliyun.1", GitCommit:"2cbb16c", GitTreeState:"", BuildDate:"2021-01-27T02:20:04Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by muvaf** [comment]
Hi @zzxwill ! Currently, the UI supports creation of resources that have UI schema defined, like [here](https://github.com/upbound/platform-ref-aws/blob/4b71ff2/database/postgres/definition.yaml#L6). The plan is to fall back to OpenAPIv3 Schema if UI schema is not available. But until then, UI schema needs to exist on the `CustomResourceDefinition` annotations.

**Comment by jbw976** [comment]
Also worth noting that there is supposed to be a tooltip message when hovering over the disabled button that explains why it's disabled.  That doesn't seem to be displaying now, so we are following up on fixing that soon. thanks!

**Comment by zzxwill** [comment]
Got it, thanks:) @muvaf @jbw976

**Comment by thephred** [comment]
Hey @zzxwill, the fix for missing tooltip message when hovering on the disabled "Create New" button that @jbw976 talked about has been fixed and is live. Thank you for your bug report, feel free to close this issue if this is resolved for you.
