### ISSUE TITLE
Versions from master not sortable as semantic versions

### ISSUE THREAD

**Issue by turkenh** [upbound/universal-crossplane#109]
### What happened?

Tag we have in master right now is `v1.3.0-up.1-rc.0`. Below you can see some of the versions we've generated from master with this version:

1.3.0-up.1.rc.0.2-ge7c4d09
1.3.0-up.1.rc.0.9-g86eba06
1.3.0-up.1.rc.0.11-ga5ee7ca
1.3.0-up.1.rc.0.22-g669eead

The problem with these versions is, they cannot be sorted properly as semantic versions. Semver libraries splits pre-release part (e.g. `up.1.rc.0.2-ge7c4d09`) with `.` and compare each piece from left to right. In this comparison, `9-g86eba06` calculated as greater than `11-ga5ee7ca` which is not correct.

This prevents finding the latest available version using standard semver libraries. 

We also saw the same problem in the output of `helm search repo` which sorts versions and the one on top expected to be the latest:

```
$ helm search repo -l upbound-main/universal-crossplane --devel

NAME                             	CHART VERSION              	APP VERSION                	DESCRIPTION
upbound-main/universal-crossplane	1.3.0-up.1.rc.0.9-g86eba06 	1.3.0-up.1.rc.0.9-g86eba06 	Upbound Universal Crossplane (UXP) is Upbound's...
upbound-main/universal-crossplane	1.3.0-up.1.rc.0.22-g669eead	1.3.0-up.1.rc.0.22-g669eead	Upbound Universal Crossplane (UXP) is Upbound's...
upbound-main/universal-crossplane	1.3.0-up.1.rc.0.20-g23d464e	1.3.0-up.1.rc.0.20-g23d464e	Upbound Universal Crossplane (UXP) is Upbound's...
upbound-main/universal-crossplane	1.3.0-up.1.rc.0.2-ge7c4d09 	1.3.0-up.1.rc.0.2-ge7c4d09 	Upbound Universal Crossplane allows you to conn...
upbound-main/universal-crossplane	1.3.0-up.1.rc.0.17-g076d121	1.3.0-up.1.rc.0.17-g076d121	Upbound Universal Crossplane (UXP) is Upbound's...
```

We should either adapt the tag we are using on master (which should contain only one hyphen, e.g. just `v1.3.0-rc.0`) or [update build submodule](https://github.com/upbound/build/pull/155) such that it is generating valid versions with this tag as well.

### How can we reproduce it?

https://play.golang.org/p/ZlzB7izzGdJ

### What environment did it happen in?

Universal Crossplane version: versions from master
Kubernetes version (`kubectl version`): NA

**Comment by muvaf** [comment]
I think we should extend the existing solution that `build` submodule uses for this problem as you did in [your PR](https://github.com/upbound/build/pull/155). Deviating from our versioning scheme only on `master` would bring more confusion IMO.

**Comment by turkenh** [comment]
> I think we should extend the existing solution that `build` submodule uses for this problem as you did in [your PR](https://github.com/upbound/build/pull/155). Deviating from our versioning scheme only on `master` would bring more confusion IMO.

Sounds good to me, marked build PR as ready for review.
