### ISSUE TITLE
Getting-Started configuration could use a logo

### ISSUE THREAD

**Issue by AaronME** [upbound/universal-crossplane#111]
### What happened?
Browsed the Registry, selected Configurations.
Saw that "getting-started" lacks a logo
![image](https://user-images.githubusercontent.com/2008996/119511498-78f7e280-bd40-11eb-86d8-a2940d08c769.png)

### How can we reproduce it?
visit https://cloud.upbound.io/browse
Select "Configurations" from Filter By / Type
Note the appearance of the "getting-started" configuration

### What environment did it happen in?
Production

Universal Crossplane version: v1.2.1-up.3
Kubernetes version (`kubectl version`):
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.17", GitCommit:"f3abc15296f3a3f54e4ee42e830c61047b13895f", GitTreeState:"clean", BuildDate:"2021-01-13T13:13:00Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/arm64"}

**Comment by jeanduplessis** [comment]
Closing the issues as its no longer relevant.
