### ISSUE TITLE
values.yaml are stale for Crossplane

### ISSUE THREAD

**Issue by hasheddan** [upbound/universal-crossplane#112]
### What happened?

The default `values.yaml` in the UXP helm chart is stale with respect to Crossplane. For instance, the [`securityContext` fields on `release-1.2`](https://github.com/upbound/universal-crossplane/blob/ff3ca301ee7d723a5ba9507dea0c8f3ff80a82fe/cluster/charts/universal-crossplane/values.yaml.tmpl#L49) do not [match those for `v1.2.1` in Crossplane](https://github.com/crossplane/crossplane/blob/69872046907843b0630e31e47e91d6c0cc23180a/cluster/charts/crossplane/values.yaml.tmpl#L47).

### How can we reproduce it?

Deploy UXP and check the `runAsUser` / `runAsGroup` fields.

### What environment did it happen in?

Universal Crossplane version: `v1.2.1-up.3`
Kubernetes version (`kubectl version`): `v1.21.0` (`v1.21.0`)

**Comment by BigSammich** [comment]
When creating the release for OLM, please clear out the `runAsUser` and `runAsGroup` related to `securityContextCrossplane` and `securityContextRBACManager`

**Comment by hasheddan** [comment]
@muvaf I wonder if we could implement some hooks in `olm-bundle` to support any operations like this?

**Comment by muvaf** [comment]
@BigSammich We can do it but could you elaborate on why you need them cleared out in OLM?

**Comment by hasheddan** [comment]
@muvaf Openshift likes to assign "random" UID / GID in a range and some clusters enforce that policy, more info [here](https://www.openshift.com/blog/a-guide-to-openshift-and-uids).

**Comment by muvaf** [comment]
@hasheddan thanks for the info! I opened https://github.com/upbound/universal-crossplane/issues/116 to track it.
