### ISSUE TITLE
Document release process and distribution channels

### ISSUE THREAD

**Issue by muvaf** [upbound/universal-crossplane#113]
### What problem are you facing?

Contributors can see how OLM bundle is made and how to validate it [here](https://github.com/upbound/universal-crossplane/tree/main/cluster/olm). AWS Marketplace is mostly UI clickops. But we just don't cover that information anywhere and I feel like it can be easily forgotten during the releases because they both involve manual steps.

### How could Universal Crossplane help solve your problem?

We should have a doc explaining how to release UXP, what to do at what step and include all distributions and their details.

**Comment by turkenh** [comment]
For Rancher Marketplace, workflow is well documented [here](https://github.com/rancher/partner-charts/tree/main-source#workflow). 

I agree that we need a single source of truth with links/steps to follow after releases.
