### ISSUE TITLE
Publish UXP to the Rancher Catalog

### ISSUE THREAD

**Issue by grantgumina** [upbound/universal-crossplane#115]
### What problem are you facing?
Enterprises use tools like Rancher Catalog to centralize management of packages installed into Kubernetes clusters, and avoid sprawl and misconfiguration at scale. By being in the Rancher Catalog, Rancher customers have a frictionless way of installing UXP to their application clusters so developers can self-service infrastructure.

**Comment by grantgumina** [comment]
Left a review with a few minor suggestions https://github.com/rancher/partner-charts/pull/89#pullrequestreview-670516271

**Comment by turkenh** [comment]
Rancher PR got merged and UXP is now listed as a partner chart in the marketplace.
