### ISSUE TITLE
Stable versions are pre-release versions as per semver specification

### ISSUE THREAD

**Issue by turkenh** [upbound/universal-crossplane#119]
### What happened?

We are [versioning](https://github.com/upbound/universal-crossplane/blob/main/design/design-packaging.md#versioning) our stable artifacts in the following format: `x.y.z-up.n`. However, as per [semver specification](https://semver.org/#spec-item-9), these versions considered to be `pre-release`. 

This is fine as long as we consume uxp packages via `up` cli, however, causing problems when they need to be consumed by external tooling. 

We've been observing this problem with `helm` cli, however, `up` cli being our primary installation method and helm having `--devel` option as a workaround, this considered as a low priority issue so far.

Now, I am having a similar problem while working on [publishing UXP to Rancher catalog](https://github.com/upbound/universal-crossplane/issues/115). UXP charts with the current version format not visible in the UI unless the user intentionally enables "Include Prerelease Versions" option under preferences.

### How can we reproduce it?

```
$ helm repo add upbound-stable https://charts.upbound.io/stable && helm repo update

$ helm search repo -l upbound-stable/universal-crossplane
No results found

$ helm search repo -l upbound-stable/universal-crossplane --devel
NAME                               	CHART VERSION	APP VERSION	DESCRIPTION
upbound-stable/universal-crossplane	1.2.1-up.3   	1.2.1-up.3 	Upbound Universal Crossplane allows you to conn...
upbound-stable/universal-crossplane	1.2.1-up.2   	1.2.1-up.2 	Upbound Universal Crossplane allows you to conn...
upbound-stable/universal-crossplane	1.2.1-up.1   	1.2.1-up.1 	Upbound Universal Crossplane allows you to conn...
```

### What environment did it happen in?

Universal Crossplane version: 1.2.1-up.3
Kubernetes version (`kubectl version`): N/A

**Comment by turkenh** [comment]
I see the following options here:

**a.** Keep current versioning and we are good with `up` cli as the main installation tool. Find workarounds for other deployment methods:
  - Document `helm` to use with `--devel`
  - [Patch version](https://github.com/rancher/partner-charts/pull/89/files#diff-d8d0a4085ea3e2ab66cca6354db4a923ae965316a9ea63e73951451f48c67380R22) in rancher marketplace, e.g. `1.2.1-up.3` --> `1.2.1003` (assuming documenting to enable "Include Prerelease Versions" option to use UXP is a no go)

**b.** Change our versioning scheme with the constraint of **first part will match full upstream crossplane version**, e.g. `x.y.z-up.n` -> `x.y.z00n`

**c.** Change our versioning scheme with the constraint of **only major.minor will match upstream crossplane version, patch is independent**, e.g. `x.y.z-up.n` -> `x.y.n`

**Comment by hasheddan** [comment]
@turkenh I don't think (c) is an option as this would be very difficult to track which patch version of Crossplane it corresponded to and would also make our requirement that upgrading from Crossplane to UXP have the same major / minor / patch require some sort of external mapping (unless we amended that rule to only require matching major / minor). For (b), it sounds unconventional, but would be valid semver and should allow us to validate versions (i.e. break on `00`). Do you know if there is any way to show pre-release versions by default in the rancher marketplace?

**Comment by turkenh** [comment]
> Do you know if there is any way to show pre-release versions by default in the rancher marketplace?

It is a [user preference](https://github.com/rancher/dashboard/blob/767f54419c8d2bd0ac8a1ac94fc0bb36c54dfe1d/store/prefs.js#L69) that is `off` by default. I don't think (couldn't find) a way to control this at chart level.

**Comment by muvaf** [comment]
Can we open an issue in the related Rancher repo about this? Semver is not strict as it uses `MAY` statement, so there might be some room there.

If we think there is no way around and we absolutely want customers to see the entry without turning pre-release option on, then option (b) sounds like the best among options that gives consistency and less confusion.

**Comment by turkenh** [comment]
> Can we open an issue in the related Rancher repo about this? Semver is not strict as it uses MAY statement, so there might be some room there.

I believe the `MAY` there is to tell semver **may** (or may not) have a prerelease part. It is not about that part **may** not be considered as a prerelease. 
Also, this is how [existing](https://play.golang.org/p/31FTkkvsND4), [semver](https://play.golang.org/p/c4Sv4igeQqa) libraries being implemented and the rancher dashboard just [rely on an existing library](https://github.com/rancher/dashboard/blob/75753f0b0eca24304e4cb00815b69018f0fab3d9/utils/version.js#L73) to parse semver. So, I don't think we can ask to make such an exception there. 

From Rancher, I can only think of asking for a chart-level option for this but this would mean we are choosing option a, which is finding workarounds to this more general problem (and we already have a workaround as mentioned). This could still be an option that we might want to choose.

**Comment by turkenh** [comment]
We have been living with this for more than 3 years without too much confusion and enough workarounds. 
Also, given there is no easy and nice solution, closing this issue was not planned.
