### ISSUE TITLE
Upbound Agent is not cleanly uninstalled

### ISSUE THREAD

**Issue by hasheddan** [upbound/universal-crossplane#161]
### What happened?

In https://github.com/upbound/universal-crossplane/pull/146 we switched to having the `bootstrapper` manage deploying the `agent` so that it wasn't sitting around idle when not connected to Upbound Cloud. However, this means that when we uninstall UXP with `up uxp uninstall` (which is using Helm under the hood), the `agent` gets left behind. We could likely address this by either manually cleaning up with the CLI (would need to be careful about doing this from a version compatibility perspective) or, for a more simple option, orphan the `Deployment` for GC by having the the `boostrapper` be a sole owner of the `agent`.

### How can we reproduce it?

`up uxp install`
`up cloud ctp attach my-ctp | up uxp connect -`
`up uxp uninstall`

### What environment did it happen in?

UXP Version: `v1.2.3-up.1`

**Comment by turkenh** [comment]
Thanks for reporting @hasheddan. 
Currently, the agent deployment owned by the control plane token secret and will be GC'd when it gets deleted.

However, your suggestion sounds reasonable. We would just need to take care of the deletion of the agent in the controller and leverage GC to clean up when agent deployment is gone (e.g. uninstall).
