### ISSUE TITLE
Maintain UXP version releases in Rancher marketplace 

### ISSUE THREAD

**Issue by robsclark** [upbound/universal-crossplane#171]
### What problem are you facing?

UXP is available in the Rancher marketplace. A process is required to lifecycle-manage / update versions on a regular basis.

### How could Upbound help solve your problem?
Put a process in place to manage the UXP listing in the Rancher marketplace

**Comment by luebken** [comment]
There is an open PR for updating to the current version https://github.com/rancher/partner-charts/pull/101

By the comment from @turkenh, the current process is not resource-intensive on our side so we don't see the benefit to automate it at this point.
