### ISSUE TITLE
UXP release for Crossplane 1.3.1

### ISSUE THREAD

**Issue by muvaf** [upbound/universal-crossplane#172]
Todo list for the release:

- [x] Cut the release on UXP repo: https://github.com/upbound/universal-crossplane/releases/tag/v1.3.1-up.1
- [x] Bump version(s) for hosted crossplanes
- [x] Publish to [OLM](https://github.com/upbound/universal-crossplane/blob/main/CONTRIBUTING.md#operator-lifecycle-manager) => [PR1](https://github.com/k8s-operatorhub/community-operators/pull/200), [PR2](https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/221)
- [x] Publish to [AWS Marketplace](https://github.com/upbound/universal-crossplane/blob/main/CONTRIBUTING.md#aws-marketplace) => Submitted and under review
- [x] Publish to [Rancher Marketplace](https://github.com/upbound/universal-crossplane/blob/main/CONTRIBUTING.md#rancher-marketplace) => https://github.com/rancher/partner-charts/pull/170

**Comment by BigSammich** [comment]
@muvaf a while back https://github.com/upbound/universal-crossplane/issues/116 was opened to address the various ```runAsUser``` and ```runAsGroup``` values set in ```securityContextCrossplane``` and ```securityContextRBACManager```. It appears that this most recent 1.3.1 release in OLM broke the changes from the #116 fix, because now 65532 is being used again for the UID and GID.

**Comment by hasheddan** [comment]
Thanks for calling this out @BigSammich and apologies for the break. This is noted in our OLM [artifact documentation](https://github.com/upbound/universal-crossplane/blob/main/cluster/olm/README.md#operator-lifecycle-manager-artifact), but could likely be called out more explicitly to ensure this does not happen. I'll make sure this gets updated in OLM repo 👍🏻

**Comment by BigSammich** [comment]
Thanks @hasheddan. Any eta on how long that fix will take? Does this need to follow your normal release process?

**Comment by hasheddan** [comment]
@BigSammich this should be addressed in the next few hours -- I believe we can update in OLM repo directly

**Comment by muvaf** [comment]
I opened the following PRs to update the OLM bundle to fix the existing version:
* https://github.com/k8s-operatorhub/community-operators/pull/213
* https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/238
