### ISSUE TITLE
Automate publishing getting started configuration package

### ISSUE THREAD

**Issue by turkenh** [upbound/universal-crossplane#184]
### What problem are you facing?

Currently, we don't have an automated workflow for build and publish getting started configuration package.

### How could Upbound help solve your problem?

We need to automate similar to how upstream [crossplane's configuration workflows](https://github.com/crossplane/crossplane/blob/master/.github/workflows/configurations.yml).

**Comment by jbw976** [comment]
@turkenh is this a dupe of https://github.com/upbound/universal-crossplane/issues/102?  If you think so, you can go ahead and close this one :)
