### ISSUE TITLE
Support custom certificates for connecting to NATS in upbound-agent

### ISSUE THREAD

**Issue by hasheddan** [upbound/universal-crossplane#194]
### What problem are you facing?

In the event that someone is running NATS using a self-signed certificate, they currently have to skip TLS verification by passing the [`--insecure` flag](https://github.com/upbound/universal-crossplane/blob/cf7e4e951e44a3eb4ada28aa8f82e70915b7ec78/cmd/upbound-agent/main.go#L66).

### How could Upbound help solve your problem?

We should allow for providing custom certificates that can be added to the trusted pool. 

Epic #

**Comment by jeanduplessis** [comment]
Closing as no longer relevant
