### ISSUE TITLE
Release v1.5.1-up1 and Publish to Marketplaces

### ISSUE THREAD

**Issue by muvaf** [upbound/universal-crossplane#196]
- [x] Release UXP v1.5.1-up.1
- [x] Update Hosted Crossplane version
- [x] Publish to [OLM](https://github.com/upbound/universal-crossplane/blob/main/CONTRIBUTING.md#operator-lifecycle-manager) 
- [x] Publish to [AWS Marketplace](https://github.com/upbound/universal-crossplane/blob/main/CONTRIBUTING.md#aws-marketplace)
- [x] Publish to [Rancher Marketplace](https://github.com/upbound/universal-crossplane/blob/main/CONTRIBUTING.md#rancher-marketplace)

**Comment by muvaf** [comment]
@turkenh I'm assigning this to myself since I'm already doing others so I'll just do that as well.

**Comment by turkenh** [comment]
SGTM, thanks @muvaf!
Please let me know if you need any help.

**Comment by muvaf** [comment]
Done! Artifacts are now in Helm, DockerHub, AWS Marketplace, Redhat OLM, OperatorHub OLM and Rancher Catalog.

https://github.com/upbound/universal-crossplane/releases/tag/v1.5.1-up.1
