### ISSUE TITLE
Release Policy

### ISSUE THREAD

**Issue by muvaf** [upbound/universal-crossplane#197]
### What problem are you facing?

Currently, it's unclear when a UXP release should follow after an upstream Crossplane release.

### How could Upbound help solve your problem?

I see two options mainly:
* Explicitly lag a single version, i.e. release UXP 1.4.0 once Crossplane 1.5.0 is released.
  * I'm not sure about this approach; at 1.5.0 we'd have patch releases of 1.4.0 for obvious bugs anyway and we'd just end up releasing later, not making huge improvements on top of the patched version.
* Have a bake period after each minor release.
  * UXP v1.5.0 can follow Crossplane v1.5.0 after exactly 2 weeks during which we fix upstream or UXP.
  * At the end of 2 weeks, we'd release the latest patch of that release, i.e. if there is a v1.5.1, there wouldn't be v1.5.0-up.1 so that people are sure that if there is a new UXP version, it's a hardened one.

I feel closer to the second option so that we can make sure if something is broken in upstream, we can keep UXP users safe from that, at least from the problems that we surface within the 2-weeks (or time we decide). In the former option, it's not really safer to use UXP if it strictly follows every release of Crossplane.

**Comment by negz** [comment]
I like the sound of the second option - the shorter bake period - too. Thanks for tracking this @muvaf.

**Comment by muvaf** [comment]
@luebken what are your thoughts regarding this from product perspective?

**Comment by luebken** [comment]
Without having enough experience, I would also vote for the second option. The faster the better.

**Comment by grantgumina** [comment]
Agree we should proceed with option 2 here. There's going to be a high rate of innovation happening with Crossplane/UXP, so the faster we can deliver value to customers, the better. If the release velocity becomes operationally difficult or customers get overwhelmed with having to make many upgrades, we can discuss other options in the future.

**Comment by muvaf** [comment]
[Here is the PR](https://github.com/upbound/universal-crossplane/pull/198) that adds this policy to README. I added a detail about what to do when there is a patch release of upstream Crossplane after UXP is released at the end of bake period. Since it's a patch version, I think we should take it and release UXP immediately. Feel free to weigh in on the PR.
