### ISSUE TITLE
Release UXP v1.6.1-up.1 on January 18, 2022

### ISSUE THREAD

**Issue by muvaf** [upbound/universal-crossplane#213]
### What problem are you facing?

Bake period for v1.6 is finished. A release of UXP is due.

### How could Upbound help solve your problem?

Release by following https://github.com/upbound/universal-crossplane/blob/main/CONTRIBUTING.md#release-process

- [x] Release UXP v1.6.1-up.1
- [ ] Publish to [OLM](https://github.com/upbound/universal-crossplane/blob/main/CONTRIBUTING.md#operator-lifecycle-manager) => PRs open: 
  - https://github.com/k8s-operatorhub/community-operators/pull/619
  - https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/657
- [x] Publish to [AWS Marketplace](https://github.com/upbound/universal-crossplane/blob/main/CONTRIBUTING.md#aws-marketplace)
- [x] Publish to [Rancher Marketplace](https://github.com/upbound/universal-crossplane/blob/main/CONTRIBUTING.md#rancher-marketplace) => https://github.com/rancher/partner-charts/pull/318

**Comment by turkenh** [comment]
UXP v1.6.1-up.1 is live: https://github.com/upbound/universal-crossplane/releases/tag/v1.6.1-up.1
