### ISSUE TITLE
Bring xgql code to this repo

### ISSUE THREAD

**Issue by muvaf** [upbound/universal-crossplane#23]
Now that [xgql](https://github.com/upbound/xgql/) is written in Go and [agent](https://github.com/upbound/wesaas/tree/master/cmd/upbound-agent) was already in Go, all parts of Universal Crossplane are written in Go. As mentioned [in design doc](https://github.com/upbound/crossplane-distro/blob/main/DESIGN.md#monorepo), I think it makes sense for us to move both xgql and agent to this repo and produce their images from here.

For versioning, @turkenh suggested using `v1.2.0-up.1` where `v1.2.0` is Crossplane version and `up.1` is distro version, similar to GKE using `1.18-gke.156`. All images (bootstrapper, agent and xgql) would use the same version tag.

**Comment by muvaf** [comment]
@negz should we close this issue?

**Comment by phisco** [comment]
Closing as `xgql` was removed in https://github.com/upbound/universal-crossplane/pull/327.
