### ISSUE TITLE
Update getting-started Configuration package to use supported postgres engine version

### ISSUE THREAD

**Issue by jastang** [upbound/universal-crossplane#238]
**Why?**
AWS RDS for PostgreSQL is [approaching end-of-life for 9.6](https://aws.amazon.com/blogs/database/upgrade-amazon-rds-and-amazon-aurora-postgresql-version-9-6/) and starting April 26, 2022, AWS will auto-upgrade RDS databases with this engine version. This will hopefully avoid surprises for new users onboarding onto Upbound Cloud / UXP from the guide.

**What?**
According to the [documentation](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.DBInstanceClass.html#Concepts.DBInstanceClass.Support), for the `db.t2.small` instance type, we will need to use an `engineVersion` < PostgreSQL 13.

Checking with `aws rds describe-db-engine-versions --engine postgres`, 12.10 is a good candidate:

```
{
            "Engine": "postgres",
            "DBParameterGroupFamily": "postgres12",
            "SupportsLogExportsToCloudwatchLogs": true,
            "SupportsReadReplica": true,
            "DBEngineDescription": "PostgreSQL",
            "EngineVersion": "12.10",
            "DBEngineVersionDescription": "PostgreSQL 12.10-R1",
            "ExportableLogTypes": [
                "postgresql",
                "upgrade"
            ],
            "ValidUpgradeTarget": [
                {
                    "Engine": "postgres",
                    "IsMajorVersionUpgrade": true,
                    "AutoUpgrade": false,
                    "Description": "PostgreSQL 13.6-R1",
                    "EngineVersion": "13.6"
                },
                {
                    "Engine": "postgres",
                    "IsMajorVersionUpgrade": true,
                    "AutoUpgrade": false,
                    "Description": "PostgreSQL 14.2-R1",
                    "EngineVersion": "14.2"
                }
            ]
        }
 ```
The `engineVersion` could be patched in from the sample XRD instead of being hardcoded [here](https://github.com/upbound/universal-crossplane/blob/87f6783fa12305368a56a86adb441e7077380cc6/docs/getting-started/configuration/composition.yaml#L139) -- I believe that we would have to build the Configuration xpkg manually, and then push and test it (e.g. from an org repo).

xref #102

**Comment by jastang** [comment]
Hello! I'm new to the community so I would welcome pairing, even though this is a small issue. I'm also not sure if this should touch `cluster/olm/` where there is another reference to 9.6.

**Comment by ytsarev** [comment]
Already fixed in upstream crossplane https://github.com/crossplane/crossplane/pull/2984 , we need an update for UXP

**Comment by jastang** [comment]
Thanks @ytsarev! Just want to confirm that backporting from upstream means no action required here (I didn't see 2984 in 1.7.0)? 

As we noted on Slack once that's done we'd still need to manually build, test, and publish the package. I'm also not sure about updating the docs for UXP as I think I read somewhere they aren't open source atm.

Let me know -- thanks!

**Comment by ytsarev** [comment]
@jastang naive `git grep` shows some documentation samples to update
```
cluster/olm/clusterserviceversion.yaml.tmpl:                      "engineVersion":"9.6",
docs/getting-started/configuration/composition.yaml:            engineVersion: "9.6"
```
I will also double check internally if some other steps are required

**Comment by jastang** [comment]
@ytsarev yep, I have those two as well. After you check internally I can open a PR for this and test with my personal registry

**Comment by jbw976** [comment]
Thank you @jastang for pointing out this issue and being willing to contribute a fix! We're happy to support your efforts here and get this contribution to the finish line.

Let's take the following steps:

1. I've added some manual building steps to #102 to give you a sense of how to build and test your private package while you're working on the fix
2. Once the fix looks good on your side, feel free to open a PR to this repo with your changes that we can review
3. After the PR is merged, an Upbounder will perform the build steps to publish an official package to the registry that the docs will pick up

Some notes:

* I don't think there's any other docs change, just the change to the composition.yaml file
* The OLM bundle stuff is more complicated, so let's put that to the side for now - perhaps we can open a specific issue to follow up on that with @turkenh?
* I'm good with leaving the engineVersion inside the composition instead of patching it in from a claim - I like the separation of concerns here where the app dev doesn't have the responsibility of picking the engine version - they get what the platform team is offering.

**Comment by jastang** [comment]
Thanks @jbw976 for the support! #243 is now open. I think `make reviewable` is only applicable to upstream crossplane but let me know if any additional details or due diligence is required.

**Comment by jbw976** [comment]
@jastang how would you feel about driving this to completion now? You could do the build/publish of this package that has your changes in it - but first it may be wise to sync up with @plumbis to see what the current status of these docs, or the plan for the near future is for them, to see if it's worthwhile to still invest in this.

What do you think? :)

**Comment by jastang** [comment]
> @jastang how would you feel about driving this to completion now? You could do the build/publish of this package that has your changes in it - but first it may be wise to sync up with @plumbis to see what the current status of these docs, or the plan for the near future is for them, to see if it's worthwhile to still invest in this.
> 
> What do you think? :)

@jbw976 happy to build+publish the updated package -- the `getting-started` docs could definitely use some love and I can compile a few issues for those. the only thing that looks like it could influence the install of the Configuration is the reference to https://raw.githubusercontent.com/upbound/universal-crossplane/main/docs/getting-started/install.yaml which seems to use `registry.upbound.io` instead of `xpkg.upbound.io` -- I think that should be updated (or removed?)

**Comment by jbw976** [comment]
good catch @jastang, it makes total sense to update https://raw.githubusercontent.com/upbound/universal-crossplane/main/docs/getting-started/install.yaml to match what's shown in the code block here: 
https://cloud.upbound.io/docs/getting-started/build-control-plane/#install-a-configuration

They are supposed to be the same thing I think, and that code block within the docs is using xpkg.upbound.io.  Makes sense to also update the install.yaml.

Another place to update (that it looks like we missed) would be the reference to `9.6` that's still in https://cloud.upbound.io/docs/uxp/build-configuration/#define-a-composite-resource.  Oops 😊 

I'm hoping the manual building steps captured in the description of #102 would still work well here - let me know if you encounter any issues.  Basically do the following:

1. Build the package and publish it to your own test org in UbC
1. Install the test package from your test org and make sure it's successful and healthy
    * Use the steps in https://cloud.upbound.io/docs/getting-started/build-control-plane, but remember to point it at your test org
1. If all is OK, push the exact same test package to its official home at xpkg.upbound.io/upbound/getting-started:latest

**Comment by jastang** [comment]
Verified successful installation (via manifest and console UI) of xpkg: 

<img width="899" alt="Screen Shot 2022-07-22 at 2 24 44 PM" src="https://user-images.githubusercontent.com/2058247/180500916-7a76741f-577c-4cdb-93f0-e9eef2d6b1ab.png">

Going to push v0.0.5 + latest now.

**Comment by jastang** [comment]
`:v0.0.5` looks good; will push to `:latest` as well.

```
➜  configuration git:(main) ✗ k get pkg
NAME                                               INSTALLED   HEALTHY   PACKAGE                                           AGE
configuration.pkg.crossplane.io/getting-started    True        True      xpkg.upbound.io/upbound/getting-started:v0.0.5    20s
```

https://explore.ggcr.dev/?repo=xpkg.upbound.io%2Fupbound%2Fgetting-started

**Comment by jastang** [comment]
`:latest` also looking good:

```
➜  getting-started git:(main) ✗ k get pkg

NAME                                               INSTALLED   HEALTHY   PACKAGE                                           AGE
configuration.pkg.crossplane.io/getting-started    True        True      xpkg.upbound.io/upbound/getting-started:latest    16s
```

Also verified manifests match:
https://explore.ggcr.dev/?image=xpkg.upbound.io/upbound/getting-started:latest
https://explore.ggcr.dev/?image=xpkg.upbound.io/upbound/getting-started:v0.0.5

**Comment by jastang** [comment]
@jbw976 I think we are good to go! check my paper trail of due diligence and feel free to do the honours of closing this out.

**Comment by jbw976** [comment]
Thanks for the follow up on this @jastang! Your details shown look good to me, and I also took a look inside the package with `up xpkg xp-extract xpkg.upbound.io/upbound/getting-started:latest`.  The engineVersion field looks correctly updated inside the package's contents.
```
grep -F -i 'engineVersion' out
            engineVersion: "12.10"
```

Let's close this out but open a new docs issue for the old engineVersion field we missed in https://cloud.upbound.io/docs/uxp/build-configuration/#define-a-composite-resource.
