### ISSUE TITLE
olm: serviceaccount duplication error

### ISSUE THREAD

**Issue by muvaf** [upbound/universal-crossplane#247]
### What problem are you facing?

The OLM bundle we're producing is not compatible anymore, see https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/863#issuecomment-1082854270

### How could Upbound help solve your problem?

Fixing the supposed duplication.

**Comment by muvaf** [comment]
Future assignee: the use case of OLM users using a private registry is disabled with https://github.com/upbound/universal-crossplane/pull/248 which is a related change. Consider bringing back the use case together with the service account fixes for this issue.

**Comment by jeanduplessis** [comment]
Closing as we are not focusing on market place publishing at the moment.
