### ISSUE TITLE
Please document sizing requirements to run UXP and lots of CRDs

### ISSUE THREAD

**Issue by bassam** [upbound/universal-crossplane#252]
UXP should clearly document its cpu, memory and other requirements. This should also factor running on different managed Kubernetes services like GKE, EKS and AKS. Also when loading providers that have lots of CRDs.

**Comment by upbound-scott** [comment]
@bassam who should be assigned to this one?

**Comment by cwilhit** [comment]
We've taken a first pass here. Still work in progress, but hope to have it finalized by SKO:

https://www.notion.so/upbound/Universal-Crossplane-UXP-2aa36abcf141437987ff81495ea00445#3fb7955e78e44c189ebf34eedd60e654

**Comment by negz** [comment]
@cwilhit do you think we can close this tracking issue out?
