### ISSUE TITLE
Release UXP v1.9.0-up.1 on July 28

### ISSUE THREAD

**Issue by negz** [upbound/universal-crossplane#261]
### What problem are you facing?

Crossplane v1.9.0 was just released. We should release v1.9.0-up.1 in two weeks.

### How could Upbound help solve your problem?

Release by following https://github.com/upbound/universal-crossplane/blob/main/CONTRIBUTING.md#release-process

PRs we want to ensure to include in the v1.9 release:

* https://github.com/upbound/universal-crossplane/pull/265 (in UXP, backported to all active branches)
* https://github.com/upbound/universal-crossplane/pull/262 (in UXP, backported to all active branches)
* https://github.com/crossplane/crossplane/pull/3176 (in upstream Crossplane, master only)

Task list:

- [ ] Release UXP v1.9.0-up.1
- [ ] Publish to [OLM](https://github.com/upbound/universal-crossplane/blob/main/CONTRIBUTING.md#operator-lifecycle-manager) 
- [ ] Publish to [AWS Marketplace](https://github.com/upbound/universal-crossplane/blob/main/CONTRIBUTING.md#aws-marketplace)
- [ ] Publish to [Rancher Marketplace](https://github.com/upbound/universal-crossplane/blob/main/CONTRIBUTING.md#rancher-marketplace)

**Comment by negz** [comment]
I'd like to make sure we get https://github.com/upbound/universal-crossplane/issues/260 into the upcoming release.

**Comment by negz** [comment]
Crossplane release issue: https://github.com/crossplane/crossplane/issues/3169

**Comment by jbw976** [comment]
@stevendborrelli is interested in taking this on next week - this will be great for the cac-squad to have experience with.  We'll get some help from our cp-squad friends to get this done :)

**Comment by negz** [comment]
I just raised https://github.com/upbound/universal-crossplane/issues/264, this is another release blocker that we'll need to tackle today.

**Comment by muvaf** [comment]
All limit&requests PRs are merged and also backported to 1.7 and 1.8.

@stevendborrelli Once you sync the crossplane fork with upstream (step called `Update Crossplane Version`), https://github.com/crossplane/crossplane/pull/3176 will end up in main and be part of the release `v1.9.0-up.1` without requiring any special steps. I don't think we need to patch earlier versions with that change since it's more of a new feature whereas the bumps were fixing more of an immediate problem. But if you think it should go into our patch releases as well, then you'll need to cherry-pick the commits of https://github.com/crossplane/crossplane/pull/3176 to release branches in our fork and then continue with the steps.

**Comment by jbw976** [comment]
I took a pass through the comments in this issue to identify all the PRs we want to include in this v1.9 UXP release, and I've added them to the issue description so they are summarized in one place.  The only fix I'm confused about how it will be included is https://github.com/crossplane/crossplane/pull/3176.

2 high level areas I need some help understanding are included in sections below, your guidance is appreciated @muvaf @turkenh 😇 🙏 

### Including upstream crossplane #3176

I'm having trouble understanding how https://github.com/crossplane/crossplane/pull/3176 will make it into the v1.9 release without any extra steps - it's only in upstream crossplane's master branch right now, it's not part of upstream's [release-1.9 branch](https://github.com/crossplane/crossplane/tree/release-1.9).  Am I missing something with my understanding of the flow below?

* We will create a new downstream 1.9 branch and sync it with upstream's 1.9 branch (which doesn't have the fix)
* We run the release for UXP v1.9 and use our downstream 1.9 branch (which also doesn't have the fix)
* The resultant UXP v1.9 release will not have the fix

### Including downstream specific changes

Is there any additional guidance on how we can know the set of "upbound/crossplane specific changes" to cherry pick into the new upbound/crossplane 1.9 release branch? I'm referring to this comment in https://github.com/upbound/universal-crossplane/blob/main/CONTRIBUTING.md#sync-a-new-release-branch:

```
# Cherry-pick upbound/crossplane specific changes - makefile, workflow and readme updates
```

**Comment by stevendborrelli** [comment]
[UI Upstream diffs from 1.8.1 -> 1.9.0](https://github.com/crossplane/crossplane/compare/v1.8.1...v1.9.0)

```
6bef24f251f19b66a3e0d8465942e4835f7bd54d Pin docs to v1.9.0
53236527e964ec8a23f2df76dfedaad4538a0134 Merge pull request #3171 from crossplane/backport-3164-to-release-1.9
b36da57e626430271a11f750db44cc7ab7116905 Support regexp capture groups
d8cfabe3dc2e5ac55e2d763b8a81440a2d56ce2b Handle regexps that don't match
28769975c4d1e9ec45c85330cedff00d3f2395e3 Ensure Regexp string transform is propagated to CompositionRevisions
9a3a8a4f45bff6a0abe7d3906043641ac0345bdc Add regexp support for string transofrm
1c57786e35195bef0875adf1765e5c5c02f477a2 Merge pull request #3158 from negz/differences
8e8346bf036a1e46470bd0efd53509c38cf340f3 Cleanup some Composition type and constant names
4868fe0a20b1658b67daa9136f5685fabb45da1a Fix string transform propagation
3e70239d81cd81e5625909709cda90c87f4fcc03 Merge pull request #2791 from EdgeJ/edgej/patch-multiple-arrays
998ae5d3ff32400aac11e5e43d0a233e9525b855 Pass MergeOptions when patching wildcarded paths
41e54abf4165d785f48ecd6d4f7c70ef0eb9b377 Merge pull request #3153 from hasheddan/botocore-you-fiend
6bfa26beff9f087c008caf37f3dec6fe27a8369f Add AWS_DEFAULT_REGION to fix AWS CLI bump
5bfba85669acbf8758d0698ce325533be44f4520 Merge pull request #3151 from hasheddan/fix-reconcile-rate-helm
c732ec380a1edb608a9df0052e02c2e2d47dc82a Revert "chore(helm): add arg '--max-reconcile-rate' to crossplane deployment"
d1e3547fbb292bb6259338fed6efcbc872bcfec3 Merge pull request #3141 from hasheddan/rm-extraneous-env-var
a34ed3ae7959fc1154cf6880311d72749aa10a98 Remove extraneous env var on Crossplane deployment
60fc7df4b3c9d0f11e9ea719b63b52bec56d3853 Merge pull request #3135 from hasheddan/rds-typo
58cb0c71b7b8857b04180f7e5d0bd76fdff9db8c Fix CloudSQL link in managed resource docs
8798cb94372fb8627e1bfc42a93441ec4b6b27cc Fix RDS instance link in managed resources doc
9fad746cf49633f6ba3af3c59e9e33b965980284 Merge pull request #3132 from renescheepers/renescheepers/fix_docs_links
a25b51dc06c0c006ed62f8bf7636787587a15407 docs: fix broken named links on concepts/managed-resources.
863b9cdb0a4ac0abab410038bc2f1e95cbcf90fc Merge pull request #3124 from renescheepers/renescheepers/issue_3123_annotations
5b984f672c41fff26eef7d4653c10b7ca40440b8 Remove propagation of annotations to CRDS from CompositeResourceDefinitions.
78bd6480869ffb38a694da9a8ede9a4f545f70d2 Fix incorrect language in composition readme
738bf1545488e82d6a7a671513f9cc776968a480 Fix formatting for wildcard expansion error
1ceaa00b425d567774f959adedd9054d8093d2b3 Patch multiple array fields when passed a wildcarded path
d699cf9c6772f0521f2309e1a42daf4361c59052 Merge pull request #3125 from hasheddan/xpkg-spec-typo
1afcd36271a1fc48fe5b20d31d1edf8afd1db73a Fix small typo in xpkg spec
243f1f47ca0b17503b08ef77770f41a89defeb82 Merge pull request #3103 from hasheddan/panic-in-the-lock
83ef134a072a8e785452dd22d1e9ff784b6ad87c Use test logger with discarded output in all reconciler tests
6b1e057f96d337325f631a9deb9653bbfa0a618b Fix logger panic when no version supplied in lock
1452d1f9787bd71b3417c9e7e0f2c3bc0d013b9d Merge pull request #3098 from smileisak/feat/bump-go-containerregistry-version
87e340eeda57560d7e273256d17358e2f233d1f7 Add generated CRD to fix check diff issue.
37295e691f639d543b9b14fe13f3f4a941cf096c Use go-googlecontainerregistry v0.9.0 instead of the incremental version.
94b87d78b200fc7c2bee83231a37f800e02f4a7c Bump go-containerregistry version to use Kubernetes Secrets before cloud specific auth methods
54164c3f8f2ec38a437fb343a986eb57db083b1f Merge pull request #3091 from jbw976/update-deps
786a65d381e9bf6a9299e0bbee0918d493d6e278 Bump crossplane-runtime to v0.16.0
1db9ad1f99d33cca59f442919b71cfee98a308c0 Merge pull request #3090 from jbw976/empty-for-1.8
68f6d54d1f5cc2740afff0945bfaeb8568bcb74d Empty commit ahead of the 1.8 release
```

**Comment by muvaf** [comment]
> We run the release for UXP v1.9 and use our downstream 1.9 branch (which also doesn't have the fix)

@jbw976 Sorry for the confusion, you're right! We need to cherry-pick the changes to `release-1.9` in `upbound/crossplane` from `master` branch to get those fixes.

> Is there any additional guidance on how we can know the set of "upbound/crossplane specific changes"

That's the only commit you need to cherry-pick, so running the commands in that block should be enough.

**Comment by stevendborrelli** [comment]
Upstream master sync PR https://github.com/upbound/crossplane/pull/47

**Comment by jbw976** [comment]
I see the release notes on https://github.com/upbound/universal-crossplane/releases/tag/v1.9.0-up.1, hooray!! 🎉 

Is there more to do to close out this issue @stevendborrelli? Do you want to announce and make a bit more noise about this? e.g. the #upbound channel on Crossplane slack is reasonable, the Upbound twitter is reasonable, etc. :)

**Comment by stevendborrelli** [comment]
We have a new release 1.9.0-up.2. I will put in the PRs for OLM and the AWS marketplace as per the Contribution guide and then close out this issue.

**Comment by stevendborrelli** [comment]
Closing.With the v1.9.0-up.2 release.
