### ISSUE TITLE
UXP v1.9 unexpectedly missing package manager context deadline fix

### ISSUE THREAD

**Issue by negz** [upbound/universal-crossplane#280]
### What happened?

Per https://github.com/upbound/universal-crossplane/issues/261 we had intended to cherry-pick https://github.com/crossplane/crossplane/pull/3176 into UXP v1.9.0-up.1, despite that fix not making it in quite in time for Crossplane v1.9.0.

Per https://github.com/crossplane/crossplane/issues/2564#issuecomment-1218758847, for reasons I don't quite understand yet, neither UXP v1.9.0-up.1 or v1.9.0-up.2 appear to actually have this fix. Per https://github.com/upbound/crossplane/pull/48 the code seems to be there in the release-1.9 branch of UXP.

### What environment did it happen in?

See https://github.com/crossplane/crossplane/issues/2564#issuecomment-1218758847, but essentially:

1. `kind create cluster --image kindest/node:v1.24.0`
2. Install one of the versions mentioned above.
3. Use the below commands to install some really big providers
4. `kubectl get events --watch` and wait a while - if you're on UXP you should see `cannot establish control of object: client rate limiter Wait returned an error: rate: Wait(n=1) would exceed context deadline`. If you're on upstream Crossplane (e.g. `crossplane/crossplane:v1.10.0-rc.0.31.g781e909f`) you won't.

```console
kubectl crossplane install provider crossplane/provider-jet-gcp:v0.2.0-preview
kubectl crossplane install provider crossplane/provider-jet-azure:v0.11.0-preview
kubectl crossplane install provider crossplane/provider-jet-aws:v0.4.0-preview
```

**Comment by negz** [comment]
```
  Warning  LintPackage  21s (x3 over 21s)  packages/configurationrevision.pkg.crossplane.io  incompatible Crossplane version: package is not compatible with Crossplane version (v1.9.0-up.2)
```

I used the horrible hack outlined in https://github.com/crossplane/crossplane/issues/3239 to confirm that the version of Crossplane that is inside of the Docker image we're running (`upbound/crossplane:v1.9.0-up.2`) does indeed appear to at least think it's v1.9.0-up.2. 

That's set using `GO_LDFLAGS`. I do notice that in the v1.9.0-up.2 tag we use `-X $(GO_PROJECT)/internal/version.version=$(VERSION)`, whereas in master we're using `-X $(GO_PROJECT)/internal/version.version=$(shell echo $(VERSION) | sed 's/[\.,-]up.*//' )`.

https://github.com/upbound/crossplane/blob/v1.9.0-up.2/Makefile#L32
https://github.com/upbound/crossplane/blob/master/Makefile#L32

**Comment by negz** [comment]
Just ruling out another theory - I had been using the below Helm values with upstream Crossplane, which give the pods a little more resources than UXP gets. I just tried `up uxp install --file vals.yaml` to install v1.9.0-up.2 and I'm still seeing the issue, so the problem doesn't appear to be the slightly tighter resource limits.

```yaml
$ cat vals.yaml
resourcesCrossplane:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 1000m
    memory: 1Gi

resourcesRBACManager:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi


args:
- "--debug"
```

**Comment by negz** [comment]
A sample from the logs. Somewhere we're hitting https://cs.opensource.google/go/x/time/+/e5dcc9cf:rate/rate.go;l=260.

```
1.660807167878926e+09   ERROR   crossplane.controller.packages/providerrevision.pkg.crossplane.io       Reconciler error        {"reconciler group": "pkg.crossplane.io", "reconciler kind": "ProviderRevision", "name": "crossplane-provider-jet-aws-f239dd9d0222", "namespace": "", "error": "cannot establish control of object: client rate limiter Wait returned an error: rate: Wait(n=1) would exceed context deadline"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /home/runner/work/crossplane/crossplane/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /home/runner/work/crossplane/crossplane/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:227
1.660807167878964e+09   DEBUG   crossplane.events       Warning {"object": {"kind":"ProviderRevision","name":"crossplane-provider-jet-aws-f239dd9d0222","uid":"7a5b998e-1d5b-4c00-8f84-d0c097c04206","apiVersion":"pkg.crossplane.io/v1","resourceVersion":"7576"}, "reason": "SyncPackage", "message": "cannot establish control of object: client rate limiter Wait returned an error: rate: Wait(n=1) would exceed context deadline"}
1.6608071678790517e+09  DEBUG   crossplane      Reconciling     {"controller": "packages/providerrevision.pkg.crossplane.io", "request": "/crossplane-provider-jet-aws-f239dd9d0222"}
I0818 07:19:28.759010       1 request.go:601] Waited for 1.501756584s due to client-side throttling, not priority and fairness, request: PUT:https://10.96.0.1:443/apis/apiextensions.k8s.io/v1/customresourcedefinitions/reservations.compute.gcp.jet.crossplane.io?dryRun=All
I0818 07:19:38.802465       1 request.go:601] Waited for 1.495071917s due to client-side throttling, not priority and fairness, request: PUT:https://10.96.0.1:443/apis/apiextensions.k8s.io/v1/customresourcedefinitions/nfsfileshares.storagegateway.aws.jet.crossplane.io?dryRun=All
I0818 07:19:48.852712       1 request.go:601] Waited for 1.495356709s due to client-side throttling, not priority and fairness, request: PUT:https://10.96.0.1:443/apis/apiextensions.k8s.io/v1/customresourcedefinitions/serviceiammembers.cloudrun.gcp.jet.crossplane.io?dryRun=All
I0818 07:19:58.902417       1 request.go:601] Waited for 1.493242709s due to client-side throttling, not priority and fairness, request: PUT:https://10.96.0.1:443/apis/apiextensions.k8s.io/v1/customresourcedefinitions/mssqlvirtualmachines.sqlvirtualmachine.azure.jet.crossplane.io?dryRun=All
I0818 07:20:08.952316       1 request.go:601] Waited for 1.487527334s due to client-side throttling, not priority and fairness, request: PUT:https://10.96.0.1:443/apis/apiextensions.k8s.io/v1/customresourcedefinitions/firewalls.compute.gcp.jet.crossplane.io?dryRun=All
I0818 07:20:19.001936       1 request.go:601] Waited for 1.490248251s due to client-side throttling, not priority and fairness, request: PUT:https://10.96.0.1:443/apis/apiextensions.k8s.io/v1/customresourcedefinitions/imageiampolicies.compute.gcp.jet.crossplane.io
I0818 07:20:29.002700       1 request.go:601] Waited for 1.493562459s due to client-side throttling, not priority and fairness, request: PUT:https://10.96.0.1:443/apis/apiextensions.k8s.io/v1/customresourcedefinitions/appservicehybridconnections.web.azure.jet.crossplane.io?dryRun=All
I0818 07:20:39.052261       1 request.go:601] Waited for 1.494328126s due to client-side throttling, not priority and fairness, request: PUT:https://10.96.0.1:443/apis/apiextensions.k8s.io/v1/customresourcedefinitions/appintegrationaccountschemas.logic.azure.jet.crossplane.io?dryRun=All
I0818 07:20:49.102166       1 request.go:601] Waited for 1.492725001s due to client-side throttling, not priority and fairness, request: PUT:https://10.96.0.1:443/apis/apiextensions.k8s.io/v1/customresourcedefinitions/agents.dialogflowcx.gcp.jet.crossplane.io
I0818 07:20:59.152592       1 request.go:601] Waited for 1.496357792s due to client-side throttling, not priority and fairness, request: POST:https://10.96.0.1:443/apis/apiextensions.k8s.io/v1/customresourcedefinitions?dryRun=All
I0818 07:21:09.202325       1 request.go:601] Waited for 1.492615334s due to client-side throttling, not priority and fairness, request: POST:https://10.96.0.1:443/apis/apiextensions.k8s.io/v1/customresourcedefinitions?dryRun=All
I0818 07:21:19.251892       1 request.go:601] Waited for 1.494148125s due to client-side throttling, not priority and fairness, request: PUT:https://10.96.0.1:443/apis/apiextensions.k8s.io/v1/customresourcedefinitions/routernats.compute.gcp.jet.crossplane.io
```

Note that we're not seeing these particular rate-limiter logs because we have too many CRDs. This is not the discovery client, instead we're just hitting the regular client too hard (i.e. making more requests per second than the rate limiter allows).

**Comment by negz** [comment]
Ah. Pretty sure I've found the issue.

UXP v1.9.0-up.2 is built against a fairly old version of crossplane-runtime - v0.16.0. This makes sense because that's what the c/c release-1.9 branch is using too per https://github.com/crossplane/crossplane/blob/release-1.9/go.mod#L8.

Meanwhile shortly after that release branch was cut we released https://github.com/crossplane/crossplane-runtime/releases/tag/v0.17.0. Notably that includes https://github.com/crossplane/crossplane-runtime/pull/338, which bumps the client-side rate limits up, which we had found was necessary with the more aggressive creation of MR CRDs.

My bad - I had forgotten that https://github.com/crossplane/crossplane/pull/3176 depended on https://github.com/crossplane/crossplane-runtime/pull/338 and thus didn't mention we needed to include it in https://github.com/upbound/universal-crossplane/issues/261.

**Comment by stevendborrelli** [comment]
@negz thanks for diving into this! Is PR https://github.com/crossplane/crossplane/pull/3183 the proper one for this change? There are a number of other changes in that PR and I was wondering if they all need to be applied to the 1.9 branch.

**Comment by negz** [comment]
@stevendborrelli No problem. That is the relevant PR. At a glance I'm pretty sure everything except the build submodule bump is necessary (that was only necessary for me due to my local setup not having a `/bin/bash`).

**Comment by negz** [comment]
This was fixed by https://github.com/upbound/universal-crossplane/pull/281 🎉
