### ISSUE TITLE
Document the UXP release process

### ISSUE THREAD

**Issue by jeanduplessis** [upbound/universal-crossplane#284]
### What problem are you facing?

The release process information for UXP is sparse and not very clear.

Some questions that have been raised around the release process:
- I read on the [UXP GitHub page](https://github.com/upbound/universal-crossplane) that UXP is released after a two-week bake period. What kinds of testing and validation do we do during that bake period?
- If there is a critical bug fix in Crossplane (e.g. security), will we shorten the baking period?
- The orchestration team is a customer of UXP: what is the best way for us to be informed of new UXP releases?

We should provide clear information about the release process and how we do releases.

### Definition of done

1. A new internal releases page added to Notion similar to the [Official Provider releases](https://www.notion.so/upbound/Releases-c8efa712049b4e819545c9b8b0ec57ae) (Upbound Internal) page.
1. Project README should be updated to be clear on the release process.

**Comment by jeanduplessis** [comment]
@phisco, I'm assigning this old issue to you in the context of your recent focus on the UXP release process. Some of it might not be relevant anymore so feel free to edit/ignore as needed.

**Comment by phisco** [comment]
I would also take the chance to improve the overall flow, maybe I can put together a proposal for it in this sprint.

**Comment by phisco** [comment]
Created dedicated Issue to track improvements on the sync procedure: [Improve u/xp fork sync procedure](https://github.com/upbound/crossplane/issues/72)

**Comment by phisco** [comment]
PR: https://github.com/upbound/universal-crossplane/pull/331
