### ISSUE TITLE
Consider accelerating pull secrets on Crossplane SA into universal-crossplane patches

### ISSUE THREAD

**Issue by hasheddan** [upbound/universal-crossplane#289]
### What problem are you facing?

https://github.com/crossplane/crossplane/pull/3332 was recently merged into Crossplane and will be included in the v1.10 release. However, we would like to be able to get this functionality to consumers earlier.

### How could Upbound help solve your problem?

We should consider accelerating this feature into the upcoming patch releases of universal-crossplane.

**Comment by muvaf** [comment]
Sounds good to me. Would you plan to tackle this or should we look into whether we have the room in the upcoming sprint?

FWIW, v1.10 will be released on October 18, so when the new version of UXP lands, we may release the Crossplane version to include the change after just a few days.

**Comment by hasheddan** [comment]
> Sounds good to me. Would you plan to tackle this or should we look into whether we have the room in the upcoming sprint?

I am happy to take this 👍🏻 It looks like #285 #286 #287 are unassigned to I can just batch this in with those.

**Comment by AaronME** [comment]
This would be a huge benefit to my team. Would love to see this in the next release of Universal Crossplane!

**Comment by turkenh** [comment]
@hasheddan IIUC this issue could be closed as completed?

**Comment by hasheddan** [comment]
@turkenh yep!
