### ISSUE TITLE
Consider removal of xgql

### ISSUE THREAD

**Issue by muvaf** [upbound/universal-crossplane#309]
### What problem are you facing?

The only consumer of xgql seems to be Upbound Cloud.

### How could Upbound help solve your problem?

We can remove xgql from UXP artifact.

cc @bassam @thephred @negz @tnthornton

**Comment by negz** [comment]
I don't think there's any (remaining) good reason to include xgql in UXP. Take this as my opinion, not an ask.

Whether xgql remains open source should be a separate discussion. I'll raise an issue for that.

**Comment by muvaf** [comment]
Thanks for the feedback folks! I have published a deprecation notice in [v1.10.1-up.1 release notes](https://github.com/upbound/universal-crossplane/releases/tag/v1.10.1-up.1). Let's remove it in v1.11.
