### ISSUE TITLE
Include latest release of xgql in new UXP release

### ISSUE THREAD

**Issue by tnthornton** [upbound/universal-crossplane#321]
### What problem are you facing?
With https://github.com/upbound/universal-crossplane/pull/320, we've added functionality to the deployment.yaml for xgql that enables liveness and readiness probes. Unfortunately xgql did not have endpoints that handle those requests until https://github.com/upbound/xgql/pull/108.

### How could Upbound help solve your problem?
We'll want to make sure to do a new release of xgql and include its tag here https://github.com/upbound/universal-crossplane/blob/main/Makefile#L29.

**Comment by hasheddan** [comment]
This is no longer relevant with https://github.com/upbound/universal-crossplane/pull/327.
