### ISSUE TITLE
Release UXP `v1.10.2-up.1`

### ISSUE THREAD

**Issue by hasheddan** [upbound/universal-crossplane#324]
### What problem are you facing?

A patch release for Crossplane was [recently published](https://github.com/crossplane/crossplane/releases/tag/v1.10.2) with fixes to constant reconciliation of package revisions.

### How could Upbound help solve your problem?

We should publish a new UXP release that consumes the fixes.

**Comment by turkenh** [comment]
Closed with https://github.com/upbound/universal-crossplane/releases/tag/v1.10.2-up.1
