### ISSUE TITLE
Add nodeSelector to xgql in helm chart

### ISSUE THREAD

**Issue by PavelPikat** [upbound/universal-crossplane#326]
### What problem are you facing?

Currently, when deploying crossplane using Helm chart in a hybrid cluster with Windows nodes, the `xgql` deployment gets scheduled on Windows nodes, and fails to deploy, because there is no Windows image.
The chart also lacks `nodeSelector` values that can be set.

### How could Upbound help solve your problem?

Add `xgql.nodeSelector` to helm chart values

**Comment by phisco** [comment]
Closing as `xgql` was removed in https://github.com/upbound/universal-crossplane/pull/327
