### ISSUE TITLE
Default helm chart values for image tags for v1.12.1-up.1 are not correct

### ISSUE THREAD

**Issue by teddyking** [upbound/universal-crossplane#374]
Hi there,

I've noticed that the default helm chart values for `image.tag` and `xfn.image.tag` do not match the corresponding git release tag for v1.12.1-up.1. Rather than v1.12.1-up.1 the values are set to v1.12.1-up.2 (see [here](https://github.com/upbound/universal-crossplane/blob/v1.12.1-up.1/cluster/charts/universal-crossplane/values.yaml#L11) and [here](https://github.com/upbound/universal-crossplane/blob/v1.12.1-up.1/cluster/charts/universal-crossplane/values.yaml#L171)). Is this intentional or something that's not quite right? Would it be possible to set these default values to the corresponding release versions for upcoming releases?

Thanks!
Ed

**Comment by turkenh** [comment]
Thanks for raising the issue.

Yes, this is intentional. 
The UXP helm chart uses the Crossplane image from the downstream fork of Crossplane, which is https://github.com/upbound/crossplane. That tag is to consume https://github.com/upbound/crossplane/releases/tag/v1.12.1-up.2

**Comment by turkenh** [comment]
We are working on improving our release process and will consider this issue as a source of confusion, thanks!
