### ISSUE TITLE
Expose Upbound Agent's access level to the frontend

### ISSUE THREAD

**Issue by negz** [upbound/universal-crossplane#39]
In https://github.com/upbound/universal-crossplane/pull/30 we address https://github.com/upbound/universal-crossplane/issues/18 by adding a `upbound.controlPlane.permission` Helm chart value that allows a platform operator to connect UXP to UBC in 'view-only' mode. View-only UXP control planes run the agent without permissions to impersonate the `upbound:edit` group, which means that UBC teams and users can only ever have view access.

In the UBC frontend we have a configuration screen that allows org owners to grant teams 'view' or 'edit' access to a particular control plane. Ideally if a UXP control plane were view-only at the RBAC level we'd prevent UBC from granting a team 'edit' access to that control plane per discussion in https://github.com/upbound/upbound-frontend/issues/1994.

Currently the front-end has no way of knowing whether a control plane is read-only. It can't see what RBAC roles and bindings exist because it doesn't have RBAC access to view those roles and bindings - we don't want to ask cluster operators for that level of access. Given that UXP is the 'source of truth' here it may make sense to expose whether a control plane is currently 'view-only' or through some more scoped mechanism - perhaps a well know ConfigMap?

**Comment by muvaf** [comment]
One way to do this is that `up cloud controlplane attach` could read the Helm values via `helm get` and see if `upbound.controlPlane.permission == view` or even better, it can check whether a `ClusterRoleBinding` with `crossplane-edit` name exists in the cluster and make the decision accordingly.

**Comment by jeanduplessis** [comment]
Closing as no longer relevant
