### ISSUE TITLE
Allow setting dnsPolicy for crossplane deployment pod in universal-crossplane chart

### ISSUE THREAD

**Issue by ravilr** [upbound/universal-crossplane#449]
### What happened?

Same issue as https://github.com/crossplane/crossplane/issues/5500#issue-2202871109  . Filing this issue to sync the upstream chart changes to here and have a uxp chart v1.15.1-up.2 patch release.

### What environment did it happen in?
UXP version: v1.15.1-up.1

**Comment by ravilr** [comment]
cc @phisco  Does the upstream crossplane chart changes gets synced to uxp chart during the next patch release process or does it have to be explicity synced through PR ? Thanks.

**Comment by phisco** [comment]
Yes, @ravilr, they do 😉

**Comment by ravilr** [comment]
this is included in https://github.com/upbound/universal-crossplane/releases/tag/v1.15.2-up.1
