### ISSUE TITLE
Helm chart?

### ISSUE THREAD

**Issue by odsevs** [upbound/universal-crossplane#469]
### What problem are you facing?
Since from my understanding UXP basically creates kubernetes resources, why isn't there a helm chart to install them?
Why do we instead need that separate "Up" CLI tool (that is not windows compatible)?

At least "classic" crossplane provided such a helm chart, at https://charts.crossplane.io/stable.
It's not clear to what extent that chart is compatible with UXP though?

### How could UXP help solve your problem?
Provide a helm chart for installation.

**Comment by phisco** [comment]
We do, have a look at the repo's README, you can see there is a reference to https://charts.upbound.io/stable

**Comment by odsevs** [comment]
I must have missed this information, thanks for the heads up.
