### ISSUE TITLE
AWS Marketplace Metering Integration

### ISSUE THREAD

**Issue by muvaf** [upbound/universal-crossplane#5]
Here is some info about getting the product listed: https://docs.aws.amazon.com/marketplace/latest/userguide/container-product-getting-started.html#container-product-load-form

That's the API we need to call from the containers to register usage: https://docs.aws.amazon.com/marketplacemetering/latest/APIReference/API_RegisterUsage.html

There are three levels where we can call this:
* From the container
  * That's the lowest level, requires using a different image specific to the marketplace
* As init/sidecar container
  * We can inject an init or sidecar container to `Deployment` of components when we build for AWS Marketplace. But that's easy to circumvent though we may not be as worried.
* Pre-install Helm hook
  * We can make Helm continue with the installation only if the registration is completed but that won't allow us to do live metering, which may not be necessary anyway.
  * But I'm a bit wary of using special Helm features in general.
* A component specific to metering
  * We can have a `Deployment` whose only job is to handle billing/metering stuff and we can reuse it in other marketplaces if needed. But this is also easy to circumvent since it'll probably give thumbs up on a CR or `ConfigMap` for Crossplane to work. Though we might find more creative solutions like key exchange that might involve changes in images.

**Comment by grantgumina** [comment]
I think we should close out this issue and tackle it when we want to enable customers to purchase Upbound subscriptions via AWS. Not a critical feature for the near term however.
