### ISSUE TITLE
Ability to deploy UXP via OLM in view-only mode

### ISSUE THREAD

**Issue by muvaf** [upbound/universal-crossplane#56]
### What problem are you facing?

Currently, the permission level is set in build time due to constraints of not having an operator and [we choose](https://github.com/upbound/universal-crossplane/pull/54#issuecomment-833102697) `edit` in build time but that doesn't allow users to install in `view` mode.

### How could Universal Crossplane help solve your problem?

There are a few options:
* Bootstrapper to manage RBAC objects, i.e. `ClusterRoleBinding` and `ClusterRole`s that we conditionally deploy.
  * The permission level would be set either on a new configuration CRD or in an existing `ConfigMap` we have, like the version `ConfigMap`.
* Have different listings in OperatorHub; Universal Crossplane - Edit, Universal Crossplane - View, Universal Crossplane.
  * Not sure if it'd be allowed and it could be confusing.
* Agent could have a `ConfigMap` that will allow users to toggle which groups to use.
  * `upbound:view` and `upbound:edit` would still be created but users would have the ability to configure which one(s) are allowed to be used through agent configuration.

**Comment by jeanduplessis** [comment]
Closing the issue as its not a focus area for now.
