### ISSUE TITLE
Manage upbound-agent deployment with bootstrapper and re-enable healthchecks

### ISSUE THREAD

**Issue by muvaf** [upbound/universal-crossplane#74]
### What problem are you facing?

They are disabled in https://github.com/upbound/universal-crossplane/pull/70 because they report `NotReady` when server is not started, which is what happens when control plane token doesn't exist. But that's a mode we want to support for OLM and Helm installations to complete without the `Secret` to allow it to be provided later.

### How could Universal Crossplane help solve your problem?

We should let bootstrapper create `Deployment` if the secret is there and re-enable the probes.

**Comment by turkenh** [comment]
@muvaf am I correct that we actually want to mostly revert #70 and let bootstrapper manage the deployment of upbound agent which will only create if the control plane token secret is there? 

If yes, I'll rename this ticket as "Manage upbound agent deployment with bootstrapper".

**Comment by muvaf** [comment]
> am I correct that we actually want to mostly revert #70 and let bootstrapper manage the deployment of upbound agent which will only create if the control plane token secret is there?

Yes. The other option is to report ready & live even though there is no control plane secret and agent sits idle but I don't think we'd want that. The only downside of the approach we're going with would be addition of `Deployment` permissions to the bootstrapper, which should be fine as long as it's constrained to its own namespace. cc @negz @hasheddan
