### ISSUE TITLE
Fix UXP logo URL

### ISSUE THREAD

**Issue by hasheddan** [upbound/universal-crossplane#89]
### What happened?

The UXP logo link the README.md points to a page on https://upbound.io that doesn't exist (i.e. https://upbound.io/uxp). 

### How can we fix it?

Update the link to the desired location.

**Comment by grantgumina** [comment]
upbound.io/products/uxp will be the link

**Comment by echarles** [comment]
upbound.io/products/universal-crossplane-uxp redirect to upbound.io

https://www.upbound.io/uxp ?

**Comment by hasheddan** [comment]
Yep I think this working correctly at this point 👍
