### ISSUE TITLE
Consider renaming repo to uxp

### ISSUE THREAD

**Issue by bassam** [upbound/universal-crossplane#90]
This is a shorter name and likely what will stick in the community. I don't believe this needs to be done for first release, just tracking here.

**Comment by negz** [comment]
My 2c: I also prefer "Universal Crossplane" here. I like that it says "Crossplane" in full for folks who aren't used to the UXP acronym. Another parallel is the GCP and AWS consoles, which seem to _mostly_ use "Kubernetes Engine" and "Elastic Kubernetes Service" in full despite folks in the know calling them GKE and EKS.
